@startuml

class CollezioneSingleton {
    -CATALOGO : CollezioneSingleton
    -films : List<Film>
    +add()
    +remove()
    +creaIteratore()
}

note right of CollezioneSingleton::creaIteratore
    return new IteratoreConcreto();
   end note

@enduml